name: Run test workflows

# on:
#   schedule:
#     - cron: "0 1 * * *"

# on: [push]


on: workflow_dispatch

# TODO: add files to /tmp

jobs:
  run-test-workflows:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: n8n
      -
        name: Checkout workflows repo
        uses: actions/checkout@v2
        with:
          repository: n8n-io/test-workflows
          path: test-workflows
      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: npm install and build
        run: |
          cd n8n
          npm install
          npm run bootstrap
          npm run build --if-present
        env:
          CI: true
        shell: bash
      - 
        name: Import credentials
        run: n8n/packages/cli/bin/n8n import:credentials --input=test-workflows/credentials.json
        shell: bash
        env:
          N8N_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
      - 
        name: Import workflows
        run: n8n/packages/cli/bin/n8n import:workflow --separate --input=test-workflows/workflows
        shell: bash
        env:
          N8N_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
      -
        name: Run tests
        run: n8n/packages/cli/bin/n8n executeBatch
        env:
          N8N_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}